#------------------------------------------------------------
# Table: Staff
#------------------------------------------------------------

CREATE TABLE PRIVILEGES(
	PRVID Int NOT NULL AUTO_INCREMENT,
	PRVNM VarChar(30) NOT NULL UNIQUE,
	CONSTRAINT PRIVILEGE_PK PRIMARY KEY (PRVID)
	
)ENGINE=InnoDB;

CREATE TABLE USERS(
	USRID Int NOT NULL AUTO_INCREMENT,
	USRNM Varchar(50) NOT NULL UNIQUE,
	USRPW Char(64) NOT NULL,
	USRPR Int NOT NULL,
	
	CONSTRAINT USERS_PK PRIMARY KEY (USRID),
	CONSTRAINT USERS_PRIVILEGE_FK FOREIGN KEY(USRPR) REFERENCES PRIVILEGES(PRVID)
	
)ENGINE=InnoDB;

INSERT INTO PRIVILEGES(PRVNM) VALUES("administrator");
INSERT INTO PRIVILEGES(PRVNM) VALUES("validator");
INSERT INTO PRIVILEGES(PRVNM) VALUES("editor");
INSERT INTO PRIVILEGES(PRVNM) VALUES("viewer");
INSERT INTO USERS(USRNM, USRPW, USRPR) 
VALUES(
	"admin", 
	"8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918", 
	(SELECT PRVID FROM PRIVILEGES WHERE PRVNM="administrator")
);